"""
Insertion des 50 scénarios AUC dans la base SQLite cdss_tmp.db
Référentiels : AUC 2009 SPECT-MPI (Hendel JACC, principal) + AUC 2024 préop (Doherty JACC)
+ double évaluation ESC 2024 CCS (Vrints) / ESC 2022 NCS (Halvorsen)
Auteur : Dr. F. AGBOTON - CHU Mohamed Lamine Debaghine
"""

from database import get_connection, init_db

SCENARIOS = [

    # ===== A. DÉTECTION CAD - PATIENT SYMPTOMATIQUE =====
    ("S001", "A. Détection CAD - Patient symptomatique", "Douleur thoracique non aiguë / équivalent angineux - Probabilité pré-test FAIBLE - ECG interprétable - Capable d'effort", "Symptômes : Oui | PPT : Faible (<15%) | ECG interprétable : Oui | Capable d'effort : Oui", 3, "RA", "AUC 2009 (Hendel)", "L'épreuve d'effort sur tapis SANS imagerie est suffisante. Imagerie non justifiée.", "IIb", "ESC 2024 §6.2 (PPT faible : test simple ou report)", "Non-adhérent", "Non"),
    ("S002", "A. Détection CAD - Patient symptomatique", "Douleur thoracique non aiguë - Probabilité pré-test FAIBLE - ECG NON interprétable OU Incapable d'effort", "Symptômes : Oui | PPT : Faible | ECG ininterprétable OU incapacité d'effort", 7, "A", "AUC 2009 (Hendel)", "Imagerie de stress justifiée car épreuve d'effort simple inadaptée.", "I", "ESC 2024 §6.3 (imagerie de stress si test d'effort inadapté)", "Adhérent", "Non"),
    ("S003", "A. Détection CAD - Patient symptomatique", "Douleur thoracique non aiguë - Probabilité pré-test INTERMÉDIAIRE - ECG interprétable - Capable d'effort", "Symptômes : Oui | PPT : Intermédiaire (15-85%) | ECG interprétable : Oui | Capable d'effort : Oui", 7, "A", "AUC 2009 (Hendel)", "Indication phare. TMP d'effort recommandée.", "I", "ESC 2024 §6.3 (SPECT classe I, niveau B pour PPT 15-85%)", "Adhérent", "Non"),
    ("S004", "A. Détection CAD - Patient symptomatique", "Douleur thoracique non aiguë - Probabilité pré-test INTERMÉDIAIRE - ECG NON interprétable OU Incapable d'effort", "Symptômes : Oui | PPT : Intermédiaire | ECG ininterprétable OU incapacité d'effort", 9, "A", "AUC 2009 (Hendel)", "Indication forte. TMP avec stress pharmacologique au Dipyridamole (Persantine).", "I", "ESC 2024 §6.3 (imagerie fonctionnelle, stress pharmacologique)", "Adhérent", "Non"),
    ("S005", "A. Détection CAD - Patient symptomatique", "Douleur thoracique non aiguë - Probabilité pré-test ÉLEVÉE - ECG interprétable - Capable d'effort", "Symptômes : Oui | PPT : Élevée (>85%) | ECG interprétable : Oui | Capable d'effort : Oui", 7, "A", "AUC 2009 (Hendel)", "TMP justifiée pour stratification du risque et localisation de l'ischémie.", "I", "ESC 2024 §6.3 (imagerie de stress pour localisation/stratification)", "Adhérent", "Non"),
    ("S006", "A. Détection CAD - Patient symptomatique", "Douleur thoracique non aiguë - Probabilité pré-test ÉLEVÉE - ECG NON interprétable OU Incapable d'effort", "Symptômes : Oui | PPT : Élevée | ECG ininterprétable OU incapacité d'effort", 8, "A", "AUC 2009 (Hendel)", "Forte indication. Discuter aussi la coronarographie directe selon profil.", "I", "ESC 2024 §6.3 (imagerie ; discuter coronarographie selon profil)", "Adhérent", "Non"),
    ("S007", "A. Détection CAD - Patient symptomatique", "Suspicion d'angor vasospastique (Prinzmetal) - ECG normal de repos", "Symptômes : Oui (atypiques au repos) | Angor vasospastique suspecté", 4, "MBA", "AUC 2009 (Hendel)", "Utilité limitée hors crise. Préférer Holter ECG / test à l'ergonovine.", "IIb", "ESC 2024 §8 (angor vasospastique : ECG/test provocation préférés)", "Non-adhérent", "Oui — ESC oriente vers Holter/test à l'ergonovine plutôt que SPECT"),
    ("S008", "A. Détection CAD - Patient symptomatique", "Douleur thoracique aiguë - SCA exclu - troponines négatives - ECG normal - Stratification ambulatoire à distance", "Douleur aiguë RÉSOLUE | SCA écarté | Stratification à distance", 7, "A", "AUC 2009 (Hendel)", "Évaluation ambulatoire à distance après écartement SCA aux urgences.", "I", "ESC 2024 §6.3 (stratification ambulatoire après exclusion SCA)", "Adhérent", "Non"),
    ("S009", "A. Détection CAD - Patient symptomatique", "Dyspnée d'effort isolée - Probabilité pré-test INTERMÉDIAIRE de CAD - ECG ininterprétable", "Symptômes : Dyspnée d'effort | PPT : Intermédiaire | ECG ininterprétable", 7, "A", "AUC 2009 (Hendel)", "La dyspnée d'effort peut être un équivalent angineux.", "I", "ESC 2024 §6.3 (dyspnée = équivalent angineux, imagerie justifiée)", "Adhérent", "Non"),
    ("S010", "A. Détection CAD - Patient symptomatique", "Syncope d'effort sans cause évidente - Suspicion d'origine ischémique", "Syncope d'effort | Bilan cardiologique initial normal", 6, "MBA", "AUC 2009 (Hendel)", "Indication discutable. Echocardiographie d'effort souvent préférée.", "IIa", "ESC 2024 §6.3 (syncope d'effort : imagerie fonctionnelle envisageable)", "Adhérent", "Non"),

    # ===== B. PATIENT ASYMPTOMATIQUE - DÉPISTAGE =====
    ("S011", "B. Patient asymptomatique - Dépistage", "Patient asymptomatique - Risque CV global FAIBLE (SCORE/Framingham)", "Symptômes : Non | Risque CV : Faible | Aucun FDR majeur", 1, "RA", "AUC 2009 (Hendel)", "Dépistage non recommandé. Aucun bénéfice démontré.", "III", "ESC 2024 §6.1 (pas de dépistage en risque faible)", "Non-adhérent", "Non"),
    ("S012", "B. Patient asymptomatique - Dépistage", "Patient asymptomatique - Risque CV global INTERMÉDIAIRE", "Symptômes : Non | Risque CV : Intermédiaire | Pas de diabète", 3, "RA", "AUC 2009 (Hendel)", "Pas de bénéfice prouvé. Privilégier le score calcique coronaire (CAC, non disponible au CHU BEO) si stratification utile.", "III", "ESC 2024 §6.1 (pas d'imagerie de dépistage systématique)", "Non-adhérent", "Non"),
    ("S013", "B. Patient asymptomatique - Dépistage", "Patient asymptomatique - Risque CV global ÉLEVÉ (incluant diabétique sans symptômes)", "Symptômes : Non | Risque CV : Élevé | OU Diabète asymptomatique", 5, "MBA", "AUC 2009 (Hendel)", "Discutable. Études DIAD et BARI-2D : pas de bénéfice systématique chez diabétique asymptomatique.", "IIb", "ESC 2024 §6.1 (diabétique/haut risque asymptomatique : non systématique)", "Non-adhérent", "Oui — AUC plus permissif (MBA) que l'ESC pour le dépistage du haut risque"),
    ("S014", "B. Patient asymptomatique - Dépistage", "Patient asymptomatique - ECG anormal de repos isolé (anomalies ST/T non spécifiques)", "Symptômes : Non | ECG repos anormal isolé", 4, "MBA", "AUC 2009 (Hendel)", "Selon nature des anomalies et contexte clinique.", "IIb", "ESC 2024 §6.1 (ECG anormal isolé : valeur limitée)", "Non-adhérent", "Oui — AUC plus permissif que l'ESC pour l'ECG douteux isolé"),
    ("S015", "B. Patient asymptomatique - Dépistage", "Patient asymptomatique - Score calcique coronaire (CAC) très élevé > 400", "Symptômes : Non | CAC > 400 Agatston", 6, "MBA", "AUC 2009 (Hendel)", "Recherche d'ischémie silencieuse possible mais non systématique.", "IIb", "ESC 2024 §6.1 (CAC élevé : ischémie silencieuse non systématique)", "Non-adhérent", "Oui — AUC plus permissif ; CAC non disponible au CHU BEO"),
    ("S016", "B. Patient asymptomatique - Dépistage", "Patient asymptomatique - Score calcique coronaire (CAC) 100-400", "Symptômes : Non | CAC 100-400 Agatston", 4, "MBA", "AUC 2009 (Hendel)", "Stratification par TMP discutable, à individualiser.", "IIb", "ESC 2024 §6.1 (CAC intermédiaire : individualiser)", "Non-adhérent", "Oui — AUC plus permissif ; CAC non disponible au CHU BEO"),
    ("S017", "B. Patient asymptomatique - Dépistage", "Patient asymptomatique - Athérosclérose extracardiaque connue (carotidienne, périphérique)", "Symptômes : Non | Maladie athéromateuse extracardiaque", 5, "MBA", "AUC 2009 (Hendel)", "Patient considéré à risque équivalent CAD. Discussion au cas par cas.", "IIb", "ESC 2024 §6.1 (athérome extracardiaque : au cas par cas)", "Non-adhérent", "Oui — AUC plus permissif que l'ESC"),
    ("S018", "B. Patient asymptomatique - Dépistage", "Patient asymptomatique avant initiation d'un programme d'activité physique INTENSE - Risque CV faible/intermédiaire", "Symptômes : Non | Activité physique intense planifiée | Risque CV faible-intermédiaire", 3, "RA", "AUC 2009 (Hendel)", "Test d'effort sans imagerie suffisant si nécessaire.", "III", "ESC 2024 §6.1 (test d'effort simple suffit avant activité)", "Non-adhérent", "Non"),

    # ===== C. BILAN PRÉOPÉRATOIRE =====
    ("S019", "C. Bilan préopératoire", "Chirurgie non cardiaque à risque FAIBLE - Patient asymptomatique", "Chirurgie : Risque faible (cataracte, endoscopie...) | Asymptomatique", 1, "RA", "AUC 2024 (Doherty)", "Aucune indication. Recommandations ESC/AHA convergentes.", "III", "ESC 2022 NCS §7 (chirurgie faible risque : pas d'imagerie)", "Non-adhérent", "Non"),
    ("S020", "C. Bilan préopératoire", "Chirurgie non cardiaque à risque INTERMÉDIAIRE - Asymptomatique - Bonne capacité fonctionnelle (METs >= 4)", "Chirurgie : Risque intermédiaire | Asymptomatique | METs >= 4 | Sans FDR actif", 2, "RA", "AUC 2024 (Doherty)", "Capacité fonctionnelle suffisante = pas d'indication d'imagerie.", "III", "ESC 2022 NCS §7 (METs ≥4 : pas d'imagerie)", "Non-adhérent", "Non"),
    ("S021", "C. Bilan préopératoire", "Chirurgie non cardiaque à risque INTERMÉDIAIRE - Asymptomatique - Capacité fonctionnelle INCONNUE ou < 4 METs - >= 1 FDR clinique (RCRI)", "Chirurgie : Risque intermédiaire | METs < 4 ou inconnu | >= 1 critère RCRI", 6, "MBA", "AUC 2024 (Doherty)", "Sera utile si modifie la prise en charge. À discuter au cas par cas.", "IIb", "ESC 2022 NCS §7 (imagerie si modifie la prise en charge)", "Adhérent", "Non"),
    ("S022", "C. Bilan préopératoire", "Chirurgie non cardiaque à HAUT RISQUE (vasculaire majeure) - Capacité fonctionnelle réduite (< 4 METs)", "Chirurgie : Haut risque (vasculaire) | METs < 4 | >= 1 critère RCRI", 8, "A", "AUC 2024 (Doherty)", "Indication classique. Modifie souvent la stratégie péri-opératoire.", "IIa", "ESC 2022 NCS §7 (haut risque + METs<4 : imagerie de stress recommandée)", "Adhérent", "Non"),
    ("S023", "C. Bilan préopératoire", "Chirurgie non cardiaque à HAUT RISQUE - Asymptomatique - Bonne capacité fonctionnelle (METs >= 4)", "Chirurgie : Haut risque | Asymptomatique | METs >= 4", 3, "RA", "AUC 2024 (Doherty)", "Bonne tolérance fonctionnelle = pas d'indication même en chirurgie à haut risque.", "III", "ESC 2022 NCS §7 (METs ≥4 : pas d'imagerie même en haut risque)", "Non-adhérent", "Non"),
    ("S024", "C. Bilan préopératoire", "Transplantation rénale - Bilan pré-greffe chez patient diabétique ou avec FDR", "Pré-transplantation rénale | Diabète OU >= 2 FDR", 7, "A", "AUC 2024 (Doherty)", "Pratique courante validée. Détection ischémie silencieuse.", "IIa", "ESC 2022 NCS §7 (greffe rénale + FDR : évaluation ischémique)", "Adhérent", "Non"),
    ("S025", "C. Bilan préopératoire", "Bilan avant chirurgie cardiaque valvulaire - Évaluation coronarienne associée", "Chirurgie cardiaque valvulaire | Bilan coronarien", 4, "MBA", "AUC 2024 (Doherty)", "Coronarographie habituellement préférée. TMP possible si CI à coronarographie.", "IIb", "ESC 2022 NCS §7 (chirurgie cardiaque : coronarographie préférée)", "Non-adhérent", "Non"),
    ("S026", "C. Bilan préopératoire", "Bilan préopératoire moins de 1 mois après une coronarographie/TMP normale", "Examen normal récent (< 1 mois) | Pas de nouveau symptôme", 1, "RA", "AUC 2024 (Doherty)", "Aucune indication. Redondance d'examen.", "III", "ESC 2022 NCS §7 (examen normal récent : redondance)", "Non-adhérent", "Non"),

    # ===== D. POST-REVASCULARISATION ASYMPTOMATIQUE =====
    ("S027", "D. Post-revascularisation asymptomatique", "Post-PCI (angioplastie) - Asymptomatique - < 2 ans après la procédure", "Post-PCI | Asymptomatique | Délai < 2 ans", 2, "RA", "AUC 2009 (Hendel)", "Indication piège fréquente. Surveillance clinique suffit.", "III", "ESC 2024 §11 (post-PCI asymptomatique <2 ans : surveillance clinique)", "Non-adhérent", "Non"),
    ("S028", "D. Post-revascularisation asymptomatique", "Post-PCI - Asymptomatique - >= 2 ans après la procédure", "Post-PCI | Asymptomatique | Délai >= 2 ans", 4, "MBA", "AUC 2009 (Hendel)", "Surveillance pouvant être discutée. À pondérer selon complexité de la PCI.", "IIb", "ESC 2024 §11 (post-PCI ≥2 ans : surveillance discutable)", "Non-adhérent", "Non"),
    ("S029", "D. Post-revascularisation asymptomatique", "Post-PCI de tronc commun OU lésion proximale IVA - Asymptomatique - Délai 6-12 mois", "Post-PCI haut risque (tronc commun / IVA proximale) | Asymptomatique | 6-12 mois", 6, "MBA", "AUC 2009 (Hendel)", "Surveillance acceptable pour stent à risque élevé.", "IIb", "ESC 2024 §11 (PCI haut risque : surveillance acceptable)", "Adhérent", "Non"),
    ("S030", "D. Post-revascularisation asymptomatique", "Post-CABG (pontage) - Asymptomatique - < 5 ans après la chirurgie", "Post-CABG | Asymptomatique | Délai < 5 ans", 3, "RA", "AUC 2009 (Hendel)", "Surveillance clinique suffisante.", "III", "ESC 2024 §11 (post-CABG <5 ans asymptomatique : pas d'imagerie)", "Non-adhérent", "Non"),
    ("S031", "D. Post-revascularisation asymptomatique", "Post-CABG - Asymptomatique - >= 5 ans après la chirurgie", "Post-CABG | Asymptomatique | Délai >= 5 ans", 6, "MBA", "AUC 2009 (Hendel)", "Risque accru de dysfonction des pontages veineux. TMP envisageable.", "IIb", "ESC 2024 §11 (post-CABG ≥5 ans : imagerie envisageable)", "Adhérent", "Non"),

    # ===== E. POST-REVASCULARISATION SYMPTOMATIQUE =====
    ("S032", "E. Post-revascularisation symptomatique", "Post-PCI - Symptômes récidivants (angor, dyspnée) - Quelque délai", "Post-PCI | Symptômes récidivants", 9, "A", "AUC 2009 (Hendel)", "Indication forte. Recherche de resténose ou progression de la maladie.", "I", "ESC 2024 §11 (symptômes récidivants post-PCI : imagerie recommandée)", "Adhérent", "Non"),
    ("S033", "E. Post-revascularisation symptomatique", "Post-CABG - Symptômes récidivants", "Post-CABG | Symptômes récidivants", 8, "A", "AUC 2009 (Hendel)", "Recherche de dysfonction des greffons ou progression sur natifs.", "I", "ESC 2024 §11 (symptômes récidivants post-CABG : imagerie recommandée)", "Adhérent", "Non"),
    ("S034", "E. Post-revascularisation symptomatique", "Post-revascularisation - Test d'effort anormal ou non concluant en suivi", "Post-revascularisation | Test d'effort anormal/équivoque", 8, "A", "AUC 2009 (Hendel)", "Complément d'imagerie justifié.", "I", "ESC 2024 §6.3 (test d'effort anormal : imagerie de confirmation)", "Adhérent", "Non"),
    ("S035", "E. Post-revascularisation symptomatique", "Post-PCI - Élévation des biomarqueurs cardiaques à distance sans contexte aigu", "Post-PCI | Élévation troponine à distance", 7, "A", "AUC 2009 (Hendel)", "Recherche d'ischémie silencieuse.", "IIa", "ESC 2024 §11 (élévation troponine à distance : recherche d'ischémie)", "Adhérent", "Non"),
    ("S036", "E. Post-revascularisation symptomatique", "Post-revascularisation incomplète - Stratification du risque à distance", "Revascularisation incomplète documentée | Patient stable", 7, "A", "AUC 2009 (Hendel)", "Évalue le retentissement fonctionnel des lésions non revascularisées.", "IIa", "ESC 2024 §11 (revascularisation incomplète : évaluation fonctionnelle)", "Adhérent", "Non"),

    # ===== F. POST-SYNDROME CORONARIEN AIGU / POST-IDM =====
    ("S037", "F. Post-syndrome coronarien aigu / post-IDM", "Post-IDM avec ST+ traité par angioplastie primaire - Coronarographie complète réalisée - Stratification pré-sortie", "STEMI traité | Coronarographie complète | Avant sortie", 3, "RA", "AUC 2009 (Hendel)", "Anatomie déjà connue. TMP redondante sauf doute sur viabilité.", "III", "ESC 2023 ACS §10 (anatomie connue : imagerie redondante)", "Non-adhérent", "Non"),
    ("S038", "F. Post-syndrome coronarien aigu / post-IDM", "Post-IDM non revascularisé (thrombolyse seule ou non revascularisation) - Stratification du risque", "IDM non revascularisé | Stratification pré-sortie ou post-sortie précoce", 8, "A", "AUC 2009 (Hendel)", "Indication forte. Recherche d'ischémie résiduelle.", "I", "ESC 2023 ACS §10 (IDM non revascularisé : ischémie résiduelle)", "Adhérent", "Non"),
    ("S039", "F. Post-syndrome coronarien aigu / post-IDM", "Post-SCA non ST+ traité - Évaluation à distance (3-6 mois)", "Post-NSTEMI/SCA ST- traité | Évaluation à distance", 5, "MBA", "AUC 2009 (Hendel)", "Selon revascularisation complète ou non.", "IIa", "ESC 2023 ACS §10 (post-SCA à distance : selon revascularisation)", "Adhérent", "Non"),
    ("S040", "F. Post-syndrome coronarien aigu / post-IDM", "Post-IDM - Recherche de viabilité myocardique (segments akinétiques)", "Post-IDM | FEVG abaissée | Segments akinétiques | Question viabilité", 7, "A", "AUC 2009 (Hendel)", "Viabilité optimale par Thallium repos-redistribution ou TEP-FDG (NON disponibles au CHU BEO) ; à défaut, SPECT Sestamibi gated de repos à interpréter avec prudence pour la viabilité.", "IIb", "ESC 2024 §6.4 (viabilité : IRM/TEP préférées à la SPECT)", "Adhérent", "Oui partielle — ESC privilégie IRM/TEP pour la viabilité (non disponibles au CHU BEO)"),
    ("S041", "F. Post-syndrome coronarien aigu / post-IDM", "Patient stabilisé après SCA - Aucun symptôme nouveau - 1 mois après revascularisation complète", "Post-SCA revascularisé complet | Asymptomatique | 1 mois", 2, "RA", "AUC 2009 (Hendel)", "Examen précoce non utile en l'absence de symptômes.", "III", "ESC 2023 ACS §10 (revascularisé complet asymptomatique : pas d'imagerie)", "Non-adhérent", "Non"),

    # ===== G. CAD CONNUE - SUIVI =====
    ("S042", "G. CAD connue - Suivi", "CAD connue - Modification ou aggravation des symptômes", "CAD connue | Symptômes nouveaux ou aggravés", 9, "A", "AUC 2009 (Hendel)", "Indication forte. Recherche de progression / nouvelle ischémie.", "I", "ESC 2024 §11 (symptômes nouveaux/aggravés : imagerie recommandée)", "Adhérent", "Non"),
    ("S043", "G. CAD connue - Suivi", "CAD connue - Asymptomatique - Suivi de routine sans événement", "CAD connue | Asymptomatique | Pas d'événement intercurrent", 3, "RA", "AUC 2009 (Hendel)", "Surveillance d'imagerie systématique non recommandée.", "III", "ESC 2024 §11 (CAD stable asymptomatique : pas d'imagerie systématique)", "Non-adhérent", "Non"),
    ("S044", "G. CAD connue - Suivi", "Sténose connue de gravité intermédiaire (40-70%) - Évaluation du retentissement ischémique", "Sténose intermédiaire 40-70% (coronarographie ou angio-TDM)", 8, "A", "AUC 2009 (Hendel)", "Recherche d'ischémie pour guider revascularisation (concept FFR-équivalent fonctionnel).", "IIa", "ESC 2024 §6.4 (sténose intermédiaire : évaluation fonctionnelle ; FFR si dispo)", "Adhérent", "Oui partielle — ESC mentionne aussi la FFR invasive (non disponible au CHU BEO)"),
    ("S045", "G. CAD connue - Suivi", "Coronarographie ancienne (> 2 ans) sans lésion significative - Patient asymptomatique", "Coro ancienne normale ou non significative | Asymptomatique", 2, "RA", "AUC 2009 (Hendel)", "Pas d'indication. Réévaluer si nouveaux symptômes.", "III", "ESC 2024 §11 (coronarographie ancienne normale, asymptomatique : pas d'imagerie)", "Non-adhérent", "Non"),
    ("S046", "G. CAD connue - Suivi", "CAD connue - Évaluation avant changement majeur thérapeutique (escalade médicamenteuse vs revascularisation)", "CAD connue | Décision thérapeutique en attente | Apport diagnostique attendu", 6, "MBA", "AUC 2009 (Hendel)", "À discuter en équipe (Heart Team).", "IIa", "ESC 2024 §11 (décision thérapeutique : imagerie pour guider la Heart Team)", "Adhérent", "Non"),

    # ===== H. INSUFFISANCE CARDIAQUE / AUTRES INDICATIONS =====
    ("S047", "H. Insuffisance cardiaque / autres indications", "Insuffisance cardiaque de novo - FEVG abaissée - Origine ischémique à déterminer", "IC nouvelle | FEVG < 50% | Étiologie inconnue", 8, "A", "AUC 2009 (Hendel)", "Recherche d'origine ischémique. Alternative : coronarographie (angio-TDM coronaire non disponible au CHU BEO).", "IIa", "ESC 2024 §6.4 / ESC 2021 HF (IC de novo : recherche d'étiologie ischémique)", "Adhérent", "Non"),
    ("S048", "H. Insuffisance cardiaque / autres indications", "Cardiomyopathie connue (non ischémique documentée) - Suivi de routine", "CMP non ischémique documentée | Suivi stable", 2, "RA", "AUC 2009 (Hendel)", "Aucune indication. IRM ou échographie préférées.", "III", "ESC 2021 HF (CMP non ischémique stable : IRM/écho préférées)", "Non-adhérent", "Non"),
    ("S049", "H. Insuffisance cardiaque / autres indications", "Évaluation de fibrillation auriculaire de novo - Recherche d'ischémie associée si suspicion clinique", "FA nouvelle | Symptômes évocateurs d'ischémie associés", 5, "MBA", "AUC 2009 (Hendel)", "Selon contexte clinique. Pas systématique.", "IIb", "ESC 2024 §6.3 (FA + suspicion d'ischémie : selon contexte)", "Adhérent", "Non"),
    ("S050", "H. Insuffisance cardiaque / autres indications", "Demande de répétition d'examen < 12 mois après une TMP normale - Pas de nouveau symptôme", "TMP précédente normale | Délai < 12 mois | Pas de nouveau symptôme", 1, "RA", "AUC 2009 (Hendel)", "Redondance d'examen. Irradiation évitable.", "III", "ESC 2024 §11 (répétition <12 mois sans symptôme : redondance)", "Non-adhérent", "Non"),
]

def seed_scenarios():
    init_db()
    conn = get_connection()
    cur = conn.cursor()
    cur.execute("DELETE FROM scenarios_auc")
    cur.executemany(
        "INSERT INTO scenarios_auc (id, categorie, contexte_clinique, variables_cles, score_auc, classification, source, note_clinique, classe_esc, reference_esc, conformite_esc, divergence_esc) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        SCENARIOS
    )
    conn.commit()
    count = cur.execute("SELECT COUNT(*) FROM scenarios_auc").fetchone()[0]
    conn.close()
    print(f"Scénarios insérés : {count}")

if __name__ == "__main__":
    seed_scenarios()
